name: Deploy React + Firebase

on:
  push:
    branches:
      - desarrollo  # 👈 rama que dispara el deploy, cambia si usas otra

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          cd consultorio-dental-frontend
          npm install
          npm run build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v2.2.0
        with:
          args: deploy --only hosting,functions
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          PROJECT_ID: consultorio-dental-2b454
